  
production:
  cloud_name: 'numair-majid123'
  api_key: '316945685729473'
  api_secret: 'Si26VqoPK2M9ChC6iGl1nhcU8b8'
  secure: true
  cdn_subdomain: true

development:
  cloud_name: 'numair-majid123'
  api_key: '316945685729473'
  api_secret: 'Si26VqoPK2M9ChC6iGl1nhcU8b8'
  secure: true
  cdn_subdomain: true