development:
  host: 'localhost'
  adapter: postgresql
  encoding: unicode
  database: pg
  pool: 5
  timeout: 5000
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

test:
  host: 'localhost'
  adapter: postgresql
  encoding: unicode
  database: pg
  pool: 5
  timeout: 5000
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
